import "./styles/globals.css";
import { Inter } from "next/font/google";
import ChakraProviders from "./ChakraProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Comment Sentiment Analyser',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ChakraProviders>
          {children}
        </ChakraProviders>
      </body>
    </html>
  );
}